sudo: false

language: haskell

ghc:
  - "8.0"
  - "7.10.3"
  - "7.8"

matrix:
  include:
    - ghc: '7.6'
      install: >
        cabal install Cabal cabal-install &&
        cabal install leancheck cmdargs # regex-tdfa
      script: >
        cat Makefile | grep -vE "(eg/speculate-reason|eg/regexes)" > Makefile.1 &&
        mv Makefile.1 Makefile &&
        make depend GHCFLAGS="-fno-warn-unrecognised-pragmas" GHCIMPORTDIRS=src:eg:tests &&
        make        GHCFLAGS="-fno-warn-unrecognised-pragmas" GHCIMPORTDIRS=src:eg:tests &&
        make test   GHCFLAGS="-fno-warn-unrecognised-pragmas" GHCIMPORTDIRS=src:eg:tests
    - ghc: '7.4'
      install: >
        cabal install Cabal cabal-install &&
        cabal install leancheck cmdargs # regex-tdfa
      script: >
        cat Makefile | grep -vE "(eg/speculate-reason|eg/regexes)" > Makefile.1 &&
        mv Makefile.1 Makefile &&
        make depend GHCFLAGS="-fno-warn-unrecognised-pragmas" GHCIMPORTDIRS=src:eg:tests &&
        make        GHCFLAGS="-fno-warn-unrecognised-pragmas" GHCIMPORTDIRS=src:eg:tests &&
        make test   GHCFLAGS="-fno-warn-unrecognised-pragmas" GHCIMPORTDIRS=src:eg:tests

install:
  - cabal install leancheck cmdargs regex-tdfa

# TODO: as a definitive solution, I should not reference the leancheck folder
# directly and instead use a installed package.  This made sense when
# Speculate/LeanCheck were in early stages of development.
script:
  - >
    cat Makefile | grep -v eg/speculate-reason > Makefile.1 &&
    mv Makefile.1 Makefile &&
    make depend GHCIMPORTDIRS=src:eg:tests &&
    make        GHCIMPORTDIRS=src:eg:tests &&
    make test   GHCIMPORTDIRS=src:eg:tests
  - >
    cabal configure --enable-tests --enable-benchmarks &&
    cabal build &&
    cabal test

notifications:
  email:
    on_failure: change
