bench/arithficial: \
  bench/arithficial.hs \
  mk/toplibs
bench/arithficial.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  bench/arithficial.hs
eg/arith: \
  eg/arith.hs \
  mk/toplibs
eg/arith-negate-abs: \
  eg/arith-negate-abs.hs \
  mk/toplibs
eg/arith-negate-abs.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/arith-negate-abs.hs
eg/arith.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/arith.hs
eg/binarytree: \
  eg/binarytree.hs \
  mk/toplibs
eg/binarytree.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/binarytree.hs
eg/bool: \
  eg/bool.hs \
  mk/toplibs
eg/bool.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/bool.hs
eg/colour: \
  eg/colour.hs \
  mk/toplibs
eg/colour.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/colour.hs
eg/Digraph.o: \
  eg/Digraph.hs
eg/digraphs: \
  eg/digraphs.hs \
  eg/Digraph.hs \
  mk/toplibs
eg/digraphs.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/digraphs.hs \
  eg/Digraph.hs
eg/insertsort0: \
  eg/insertsort0.hs \
  mk/toplibs
eg/insertsort0.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/insertsort0.hs
eg/insertsort: \
  eg/insertsort.hs \
  mk/toplibs
eg/insertsort.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/insertsort.hs
eg/length: \
  eg/length.hs \
  mk/toplibs
eg/length.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/length.hs
eg/list: \
  eg/list.hs \
  mk/toplibs
eg/list.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/list.hs
eg/minus: \
  eg/minus.hs \
  mk/toplibs
eg/minus.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/minus.hs
eg/monad: \
  eg/monad.hs \
  mk/toplibs
eg/monad.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Function/Show.hs \
  ../leancheck/src/Test/LeanCheck/Function/ShowFunction.hs \
  ../leancheck/src/Test/LeanCheck/Function.hs \
  ../leancheck/src/Test/LeanCheck/Function/ListsOfPairs.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/monad.hs
eg/oddeven: \
  eg/oddeven.hs \
  mk/toplibs
eg/oddeven.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/oddeven.hs
eg/plus-abs: \
  eg/plus-abs.hs \
  mk/toplibs
eg/plus-abs.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/plus-abs.hs
eg/pretty: \
  eg/pretty.hs \
  mk/toplibs
eg/pretty.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/pretty.hs
eg/ratio: \
  eg/ratio.hs \
  mk/toplibs
eg/ratio.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/ratio.hs
eg/regexes: \
  eg/Regex.hs \
  eg/regexes.hs \
  mk/toplibs
eg/regexes.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/Regex.hs \
  eg/regexes.hs
eg/Regex.o: \
  eg/Regex.hs
eg/Set.o: \
  eg/Set.hs
eg/sets: \
  eg/sets.hs \
  eg/Set.hs \
  mk/toplibs
eg/sets.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/sets.hs \
  eg/Set.hs
eg/speculate-reason.o: \
  tests/Test.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/speculate-reason.hs
eg/speculate-reason: \
  tests/Test.hs \
  eg/speculate-reason.hs \
  mk/toplibs
eg/string: \
  eg/string.hs \
  mk/toplibs
eg/string.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/string.hs
eg/Taut: \
  eg/Taut.hs \
  mk/toplibs
eg/Taut.o: \
  eg/Taut.hs
eg/tauts: \
  eg/tauts.hs \
  eg/Taut.hs \
  mk/toplibs
eg/tauts.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/tauts.hs \
  eg/Taut.hs
eg/tuples: \
  eg/tuples.hs \
  mk/toplibs
eg/tuples.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/tuples.hs
eg/zip: \
  eg/zip.hs \
  mk/toplibs
eg/zip.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs \
  eg/zip.hs
src/Test/Speculate/Args.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/CondReason.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/CondReason.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Engine: \
  mk/toplibs
src/Test/Speculate/Engine.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Expr/Canon.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Expr/Core.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Expr/Core.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Expr/Equate.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Expr/Ground.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Expr/Match: \
  mk/toplibs
src/Test/Speculate/Expr/Match.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Core.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Expr.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Expr/TypeInfo.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Core.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Misc.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Misc.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate: \
  mk/toplibs
src/Test/Speculate.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Pretty.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/CondReason.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Reason/Order.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Reason.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Report.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Sanity.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/SemiReason.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Utils/Class.o: \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Class.hs
src/Test/Speculate/Utils/Colour.o: \
  src/Test/Speculate/Utils/Colour.hs
src/Test/Speculate/Utils/Digraph.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Utils/List.o: \
  src/Test/Speculate/Utils/List.hs
src/Test/Speculate/Utils/Memoize.o: \
  src/Test/Speculate/Utils/Memoize.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Utils/Misc.o: \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/List.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Utils/Ord.o: \
  src/Test/Speculate/Utils/Ord.hs
src/Test/Speculate/Utils.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Utils/PrettyPrint.o: \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils/List.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Utils/String.o: \
  src/Test/Speculate/Utils/String.hs
src/Test/Speculate/Utils/Tiers.o: \
  src/Test/Speculate/Utils/Tiers.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
src/Test/Speculate/Utils/Timeout.o: \
  src/Test/Speculate/Utils/Timeout.hs
src/Test/Speculate/Utils/Tuple.o: \
  src/Test/Speculate/Utils/Tuple.hs
src/Test/Speculate/Utils/Typeable.o: \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/List.hs
tests/test-creason.o: \
  tests/Test.hs \
  tests/test-creason.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-creason: \
  tests/Test.hs \
  tests/test-creason.hs \
  mk/toplibs
tests/test-engine.o: \
  tests/Test.hs \
  tests/test-engine.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-engine: \
  tests/Test.hs \
  tests/test-engine.hs \
  mk/toplibs
tests/test-eval.o: \
  tests/Test.hs \
  tests/test-eval.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-eval: \
  tests/Test.hs \
  tests/test-eval.hs \
  mk/toplibs
tests/test-expr.o: \
  tests/Test.hs \
  tests/test-expr.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-expr: \
  tests/Test.hs \
  tests/test-expr.hs \
  mk/toplibs
tests/test-match.o: \
  tests/Test.hs \
  tests/test-match.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-match: \
  tests/Test.hs \
  tests/test-match.hs \
  mk/toplibs
tests/test-misc.o: \
  tests/Test.hs \
  tests/test-misc.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Misc.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-misc: \
  tests/Test.hs \
  tests/test-misc.hs \
  mk/toplibs
tests/test-order.o: \
  tests/Test.hs \
  tests/test-order.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-order: \
  tests/Test.hs \
  tests/test-order.hs \
  mk/toplibs
tests/Test.o: \
  tests/Test.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-reason.o: \
  tests/test-reason.hs \
  tests/Test.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-reason: \
  tests/test-reason.hs \
  tests/Test.hs \
  mk/toplibs
tests/test-stats.o: \
  tests/test-stats.hs \
  tests/Test.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-stats: \
  tests/test-stats.hs \
  tests/Test.hs \
  mk/toplibs
tests/Test: \
  tests/Test.hs \
  mk/toplibs
tests/test-utils.o: \
  tests/test-utils.hs \
  tests/Test.hs \
  src/Test/Speculate/Utils/Typeable.hs \
  src/Test/Speculate/Utils/Tuple.hs \
  src/Test/Speculate/Utils/Timeout.hs \
  src/Test/Speculate/Utils/Tiers.hs \
  src/Test/Speculate/Utils/String.hs \
  src/Test/Speculate/Utils/PrettyPrint.hs \
  src/Test/Speculate/Utils.hs \
  src/Test/Speculate/Utils/Ord.hs \
  src/Test/Speculate/Utils/Misc.hs \
  src/Test/Speculate/Utils/Memoize.hs \
  src/Test/Speculate/Utils/List.hs \
  src/Test/Speculate/Utils/Digraph.hs \
  src/Test/Speculate/Utils/Colour.hs \
  src/Test/Speculate/Utils/Class.hs \
  src/Test/Speculate/SemiReason.hs \
  src/Test/Speculate/Sanity.hs \
  src/Test/Speculate/Report.hs \
  src/Test/Speculate/Reason.hs \
  src/Test/Speculate/Reason/Order.hs \
  src/Test/Speculate/Pretty.hs \
  src/Test/Speculate.hs \
  src/Test/Speculate/Expr/TypeInfo.hs \
  src/Test/Speculate/Expr.hs \
  src/Test/Speculate/Expr/Match.hs \
  src/Test/Speculate/Expr/Ground.hs \
  src/Test/Speculate/Expr/Equate.hs \
  src/Test/Speculate/Expr/Core.hs \
  src/Test/Speculate/Expr/Canon.hs \
  src/Test/Speculate/Engine.hs \
  src/Test/Speculate/CondReason.hs \
  src/Test/Speculate/Args.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Types.hs \
  ../leancheck/src/Test/LeanCheck/Utils/TypeBinding.hs \
  ../leancheck/src/Test/LeanCheck/Utils/Operators.hs \
  ../leancheck/src/Test/LeanCheck/Utils.hs \
  ../leancheck/src/Test/LeanCheck/Tiers.hs \
  ../leancheck/src/Test/LeanCheck.hs \
  ../leancheck/src/Test/LeanCheck/IO.hs \
  ../leancheck/src/Test/LeanCheck/Error.hs \
  ../leancheck/src/Test/LeanCheck/Derive.hs \
  ../leancheck/src/Test/LeanCheck/Core.hs \
  ../leancheck/src/Test/LeanCheck/Basic.hs
tests/test-utils: \
  tests/test-utils.hs \
  tests/Test.hs \
  mk/toplibs
