#!/bin/bash
#
# bench/versions: print versions of installed dependencies
#
# Copyright (C) 2021-2024  Rudy Matela
# Distributed under the 3-Clause BSD licence (see the file LICENSE).
get-ghc-v() {
    ghc --version | sed -e "s/.* version/GHC/"
}
ghc-pkg-list() {
	ghc-pkg list "$@"
	ghc-pkg list --package-db ~/.cabal/store/ghc-$(ghc --version | sed -e "s/.* version //")/package.db "$@"
}
get-pkg-v() {
    ghc-pkg-list $1 2>/dev/null |
    grep " $1-" |
    sed -e "s/^ *//" |
    tail -1
}
get-ghc-v
for pkg in "$@"
do
	get-pkg-v $pkg
done
